language: php

php:
  - 7.4

before_script:
  - composer self-update || echo "[ERROR] update-composer failed!"
  - composer install --no-interaction --optimize-autoloader

script:
    - composer phpstan
    - composer phpcs
    - composer test ./tests/Unit

after_success:
  - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
  - php coveralls.phar --verbose --config tests/.coveralls.yml
